In [13]:
import numpy as np

In [14]:
NUM_INPUTS = 2 

weights = np.random.rand(1, NUM_INPUTS + 1) #  where one here, is the BIAS (1 of 0 position)

weights

array([[0.16862235, 0.88021139, 0.21869186]])

In [15]:
def step_functions(z):
    return 1 if z >= 1 else 0

In [16]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [17]:
def feed_forward(inputs, weights):
    inputs = np.insert(inputs, 0, 1)
    z = inputs @ weights.T
    y_hat = sigmoid(z[0])

    return y_hat

In [18]:
feed_forward(np.array([[1,1]]), weights)

np.float64(0.7803188779938054)

In [19]:
def fit(training_data, y, weights, learning_rate=0.1, epochs=10000):
    for _ in range(epochs):
        for i, data in enumerate(training_data):
            y_hat = feed_forward(data, weights)
            #print(f"{data}: {y_hat}")
            erro = y[i] - y_hat
            #print(erro)

            if abs(erro) > 0:
                input_bias = np.insert(data, 0, 1)
                weights += learning_rate * erro * y_hat * (1 - y_hat)  * input_bias
            
    return weights             

In [ ]:
training_data = [
    np.array([[1,1]]),
    np.array([[1,0]]),
    np.array([[0,1]]),
    np.array([[0,0]]),
]

y = [1,0,0,0]
print(weights)
print(feed_forward(np.array([[1,1]]), weights))
print(feed_forward(np.array([[1,0]]), weights))
print(feed_forward(np.array([[0,1]]), weights))
print(feed_forward(np.array([[0,0]]), weights))

print('-' * 10)
weights = fit(training_data, y, weights)
print(weights)
print(feed_forward(np.array([[1,1]]), weights))
print(feed_forward(np.array([[1,0]]), weights))
print(feed_forward(np.array([[0,1]]), weights))
print(feed_forward(np.array([[0,0]]), weights))


[[0.16862235 0.88021139 0.21869186]]
0.7803188779938054
----------
[[-8.31668177  5.48225485  5.48261826]]
0.9338994272339237
