In [519]:
import numpy as np

The first step, I need put the structure of my networking

In [520]:
NUM_INPUTS = 2 # I can put here, zero, one or random number for start, this only the columns number

weights = np.random.rand(1, NUM_INPUTS)

weights

array([[0.31751387, 0.43813788]])

In [521]:
def step_functions(z):
    return 1 if z >= 1 else 0

In [522]:
def feed_forward(inputs, weights):
    z = inputs @ weights.T
    y_hat = step_functions(z[0])

    return y_hat

In [523]:
feed_forward(np.array([[1,1]]), weights)

0

In [524]:
def fit(training_data, y, weights, learning_rate=0.1, epochs=10000):
    for _ in range(epochs):
        for i, data in enumerate(training_data):
            y_hat = feed_forward(data, weights)
            #print(f"{data}: {y_hat}")
            erro = y[i] - y_hat
            #print(erro)

            if abs(erro) > 0:
                for j in range(weights.shape[1]):
                    weights[0][j] = weights[0][j] + (learning_rate * data[0][j] * erro)  
            
    return weights             

In [525]:
training_data = [
    np.array([[1,1]]),
    np.array([[1,0]]),
    np.array([[0,1]]),
    np.array([[0,0]]),
]

y = [1,0,0,0]
print(weights)
print(feed_forward(np.array([[1,1]]), weights))
print('-' * 10)
weights = fit(training_data, y, weights)
print(weights)
print(feed_forward(np.array([[1,1]]), weights))


[[0.31751387 0.43813788]]
0
----------
[[0.51751387 0.63813788]]
1


In [531]:
print(feed_forward(np.array([[0,0]]), weights))

0


In [536]:
weights = np.random.rand(1, NUM_INPUTS)

training_data = [
    np.array([[100,1]]),
    np.array([[200,7]]),
    np.array([[190,50]]),
    np.array([[255,800]]),
    np.array([[300,1000]]),
    np.array([[10,70]]),
]

y = [1,1,1,0,0,0]

In [537]:
weights = fit(training_data, y, weights)

In [541]:
print(feed_forward(np.array([[10,5]]), weights))

0


1 - entry (num_inputs)
2 - weights
3 - activate functions
4 - feed forward