In [78]:
import numpy as np

In [79]:
NUM_INPUTS = 2 

weights = np.random.rand(1, NUM_INPUTS + 1) #  where one here, is the BIAS (1 of 0 position)

weights

array([[0.18198082, 0.57740831, 0.21098621]])

In [80]:
def step_functions(z):
    return 1 if z >= 1 else 0

In [81]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [82]:
def feed_forward(inputs, weights):
    inputs = np.insert(inputs, 0, 1)
    z = inputs @ weights.T
    y_hat = sigmoid(z[0])

    return y_hat

In [83]:
feed_forward(np.array([[1,1]]), weights)

np.float64(0.7251943049932615)

In [93]:
def fit(training_data, y, weights, learning_rate=0.1, epochs=10000):
    for _ in range(epochs):
        for i, data in enumerate(training_data):
            y_hat = feed_forward(data, weights)
            #print(f"{data}: {y_hat}")
            erro = y[i] - y_hat
            #print(erro)

            if abs(erro) > 0:
                input_bias = np.insert(data, 0, 1)
                weights += learning_rate * erro * y_hat * (1 - y_hat)  * input_bias
            
    return weights             

In [94]:
training_data = [
    np.array([[1,1]]),
    np.array([[1,0]]),
    np.array([[0,1]]),
    np.array([[0,0]]),
]

y = [1,0,0,0]
print(weights)
print(feed_forward(np.array([[1,1]]), weights))
print(feed_forward(np.array([[1,0]]), weights))
print(feed_forward(np.array([[0,1]]), weights))
print(feed_forward(np.array([[0,0]]), weights))

print('-' * 10)
weights = fit(training_data, y, weights)
print(weights)
print(feed_forward(np.array([[1,1]]), weights))
print(feed_forward(np.array([[1,0]]), weights))
print(feed_forward(np.array([[0,1]]), weights))
print(feed_forward(np.array([[0,0]]), weights))


[[-16.91359093  11.21933423  11.21933676]]
0.9960302719530784
0.0033539508009036135
0.0033539592325253216
4.51357610720548e-08
----------
[[-16.92030247  11.22380913  11.22381162]]
0.9960391119645313
0.0033464826573715166
0.003346490967211134
4.483384500473955e-08
